name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install FNA
      run: git submodule update --init --recursive
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
            
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test --verbosity normal
